/* Intuition-builder explainers for the SAA core modules.
 * One registerExplainer per module; each teaches the module's single most
 * load-bearing concept through one anchor analogy, deepened over 4 levels.
 *
 * NOTE on the registerWidget stub at the bottom: tools/validate.js line 169
 * checks modules+exams+diagrams+widgets when deciding whether a file
 * "registered nothing" — it does not count explainers. The stub widget uses a
 * moduleId that matches no module, so app.js never renders it anywhere
 * (module play view and the playground both filter/group by real module ids).
 * It exists purely to satisfy the validator for this explainer-only file.
 */
"use strict";

/* ================= 1. foundations — Regions/AZs and blast radius ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-foundations",
  moduleId: "foundations",
  title: "Regions, AZs, and blast radius",
  levels: [
    {
      name: "The analogy",
      html: "<p>Picture a bakery chain that refuses to ever run out of bread. It operates in many cities, and in each city it deliberately does <strong>not</strong> build one giant bakery. It builds three smaller ones in different neighborhoods, each with its own power line, its own water main, and its own delivery road. A kitchen fire guts one building? The other two keep the city fed while it is rebuilt. A storm floods the whole river district? The bakery across town on high ground never notices. An earthquake takes out the entire city? Customers in the next city over still get their morning loaves, because that city has its own three bakeries.</p><p>The owners obsess over one question for every piece of equipment, every building, every city: <em>if this exact thing fails, how much bread stops being made?</em> That question — how far the damage spreads when one thing breaks — is called <strong>blast radius</strong>, and it is the single most important instinct in this entire course.</p>"
    },
    {
      name: "The simple model",
      html: "<p>Map the bakery onto AWS:</p><ul><li>A <strong>city</strong> is a <strong>Region</strong> — a fully separate geography (us-east-1, eu-west-1) with its own everything. Regions are isolated from each other by design.</li><li>Each bakery <strong>building</strong> in a city is an <strong>Availability Zone (AZ)</strong> — one or more data centers with independent power, cooling, and networking, physically far enough apart that a fire, flood, or grid failure should not take out two at once, but close enough that fast private fiber connects them.</li></ul><p>Services live at different blast radii. An EC2 instance or an EBS volume lives in <em>one building</em> (one AZ). S3 and DynamoDB are <em>city-wide</em> (regional — they spread your data across AZs automatically). IAM, Route 53, and CloudFront are <em>chain-wide</em> (global).</p><p>The default design rule falls straight out of the analogy: never depend on a single building. Run your application in at least two AZs, and let a load balancer send customers to whichever bakeries are still standing.</p>"
    },
    {
      name: "How it actually works",
      html: "<p>An AZ is not one data center — it is a cluster of one or more, presented as a single failure domain. Most Regions have three or more AZs, connected by redundant metro fiber with round-trip latency typically around one to two milliseconds. That latency figure is the load-bearing fact: it is low enough for <strong>synchronous replication</strong>, which is why RDS Multi-AZ can commit every write to two AZs before acknowledging it, and why an ALB can spray traffic across AZs without you noticing. Between Regions, latency is tens to hundreds of milliseconds, so cross-Region replication is almost always <strong>asynchronous</strong> — a fact that quietly drives every disaster-recovery decision you will ever make.</p><p>Two mechanics worth knowing cold. First, AZ names are shuffled per account: your us-east-1a is not necessarily my us-east-1a. AWS randomizes the mapping to spread load; the stable identifier is the <strong>AZ ID</strong> (use1-az1), which you need when coordinating across accounts. Second, blast radius applies to control planes too: the systems that <em>create and modify</em> resources are regional, while the data planes that <em>run</em> them are zonal. Well-architected systems are <em>statically stable</em> — during an AZ failure they keep serving from pre-provisioned capacity in surviving AZs rather than depending on launching new instances while the control plane is under stress.</p>"
    },
    {
      name: "The sharp edges",
      html: "<p>Where people get burned:</p><ul><li><strong>Zonal resources do not travel.</strong> An EBS volume replicates only within its AZ and can only attach to instances in that AZ. Moving it means snapshotting (snapshots are regional, stored in S3) and restoring elsewhere. Subnets are also AZ-scoped — one subnet never spans AZs.</li><li><strong>Regional services can hide zonal chokepoints.</strong> A NAT Gateway lives in one AZ; if you route three AZs through it, an AZ failure severs outbound traffic for all of them. Deploy one per AZ.</li><li><strong>Inter-AZ traffic is not free.</strong> Cross-AZ data transfer is billed; chatty architectures pay a real tax for their resilience.</li><li><strong>AZ letters lie across accounts.</strong> Use AZ IDs when it matters.</li></ul><p>Where the analogy lies: separate bakery buildings imply that distance alone equals safety, but AZs in a Region share regional control planes and regional services — a bad day for a Region-wide service (famously in us-east-1) can affect every AZ at once. Also, you rarely pick a Region for distance; you pick it for <strong>data residency, service availability, and price</strong>, then design AZs for failure.</p><p><strong>Exam reflex:</strong> the phrase <em>survive an AZ failure</em> means Multi-AZ; <em>survive a Region failure, data residency, or lowest latency for global users</em> means multi-Region.</p>"
    }
  ]
});

/* ================= 2. iam — policy evaluation ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-iam",
  moduleId: "iam",
  title: "Policy evaluation: deny wins, filters versus grants",
  levels: [
    {
      name: "The analogy",
      html: "<p>Think of a private members' club with hundreds of doors. By default, every single door is locked to you — walking in wearing a nice suit gets you nothing. To pass a door, your name must appear on at least one <strong>guest list</strong> for it. Several people can write guest lists: the club can issue you a personal list of doors you may use, and the host of any particular room can add names to a list pinned to that room's door. Any one valid list gets you through.</p><p>But the club also keeps a <strong>banned board</strong> by the entrance, with photographs. If your face is on that board for a door, no guest list in the building will help you — banned beats invited, every time, no appeals.</p><p>Finally there is the <strong>fire marshal</strong>. The marshal never invites anyone to anything. He only posts rules that cap what is allowed in the building at all — and no host's invitation, however enthusiastic, can exceed the marshal's cap.</p>"
    },
    {
      name: "The simple model",
      html: "<p>The mapping:</p><ul><li>Each <strong>door</strong> is one API action on one resource (s3:GetObject on a specific bucket).</li><li><strong>Guest lists</strong> are <code>Allow</code> statements. Your personal list is an <strong>identity-based policy</strong> (attached to your user or role); the list pinned to the room is a <strong>resource-based policy</strong> (a bucket policy, a KMS key policy). Within one account, an Allow from <em>either</em> is enough.</li><li>The <strong>banned board</strong> is an explicit <code>Deny</code>. It overrides every Allow from every source, always.</li><li>The <strong>fire marshal</strong> is a <strong>Service Control Policy</strong> (org-level) or a <strong>permissions boundary</strong> (per-identity). These are <em>filters, not grants</em>: they define the maximum possible permissions, but attaching one gives nobody access to anything.</li></ul><p>Evaluation in one breath: everything starts as an implicit deny (locked door); you need at least one applicable Allow; an explicit Deny anywhere slams the door regardless; and the effective permission is the <em>intersection</em> of what the grants allow and what the filters permit.</p>"
    },
    {
      name: "How it actually works",
      html: "<p>For every request, IAM evaluates all applicable policies together, in a logical order you should be able to recite:</p><ol><li><strong>Explicit Deny check.</strong> If any policy of any type contains a matching Deny, the request is denied. Full stop.</li><li><strong>Organization filters.</strong> SCPs (and resource control policies) must allow the action, for every account in the path from the org root down. An SCP that omits the action denies it — for everyone in the account, including the account's admin users.</li><li><strong>Permissions boundary</strong>, if attached: the action must also be allowed there.</li><li><strong>Session policy</strong>, if the credentials came from an AssumeRole call that passed one: another intersection.</li><li><strong>Grants.</strong> Finally, an Allow must exist in the identity-based policy <em>or</em> (same-account) the resource-based policy.</li></ol><p>Cross-account is the key asymmetry: when the caller and the resource live in different accounts, <strong>both sides must allow it</strong> — the caller's identity policy and the resource's policy. Same-account, either suffices. Conditions (<code>aws:SourceIp</code>, tags, <code>aws:PrincipalOrgID</code>) constrain individual statements, and roles receive temporary credentials from STS — a time-boxed badge rather than a permanent membership card.</p>"
    },
    {
      name: "The sharp edges",
      html: "<p>The traps, most of which the exam tests directly:</p><ul><li><strong>Boundaries and SCPs grant nothing.</strong> An answer that says attach a permissions boundary to give access is always wrong. They only shrink.</li><li><strong>Explicit Deny is unbeatable.</strong> No Allow, no administrator policy, not even the resource owner can override it — the fix is to remove the Deny.</li><li><strong>SCPs do not touch everything.</strong> They do not apply to the management account of the org, nor to service-linked roles. Attaching an SCP to the root affects member accounts, not the management account itself.</li><li><strong>NotAction plus Allow</strong> means allow everything except — a common way to accidentally grant far too much. Read it twice.</li><li><strong>KMS key policies are their own kingdom:</strong> unlike most resources, a key policy must grant access explicitly or even same-account IAM policies do not work by default.</li></ul><p>Where the analogy lies: real guest lists name people, but IAM statements can match on conditions — source IP, VPC endpoint, tags, time — so the same person is admitted at one door and refused at the identical door reached through a different corridor. And the club has one entrance; AWS evaluates the union of many policy documents on every single API call, millions of times per second.</p><p><strong>Exam reflex:</strong> explicit deny always wins; SCPs and permissions boundaries filter but never grant; cross-account needs an Allow on both sides.</p>"
    }
  ]
});

/* ================= 3. vpc — routing + stateful gates ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-vpc",
  moduleId: "vpc",
  title: "What a VPC actually is: routing plus stateful gates",
  levels: [
    {
      name: "The analogy",
      html: "<p>Your company rents an entire floor of an office tower and gets to design it from scratch: how many rooms, how the mail carts move between them. At every corridor junction stands a <strong>signpost</strong> telling carts where to go next — carts have no intelligence, they just obey the most specific signpost entry that matches their destination.</p><p>Crucially, the floor starts with <strong>no connection to the street</strong>. If you want one, you install it: a <strong>front lobby</strong> where outsiders can come in and your people can go out, or a <strong>mail-room clerk</strong> who sends letters out on your behalf and accepts only the replies — strangers cannot use the clerk to get in.</p><p>Each office door has a <strong>doorman with a perfect memory</strong>: he checks who may enter, and once he has let a visitor in, he automatically lets that visitor's replies back out without re-checking. The corridor <strong>turnstiles</strong>, by contrast, have amnesia — they check every cart in both directions against a numbered printed rulebook, no memory of what passed a second ago.</p>"
    },
    {
      name: "The simple model",
      html: "<p>The floor is your <strong>VPC</strong>: a private IP range (CIDR block) that you own and carve up. The rooms are <strong>subnets</strong>, each living in exactly one Availability Zone. The signposts are <strong>route tables</strong> — every subnet consults exactly one, and packets simply follow the most specific matching route.</p><ul><li>The front lobby is the <strong>Internet Gateway</strong>: two-way street access for things with public addresses.</li><li>The mail clerk is the <strong>NAT Gateway</strong>: private instances can initiate outbound traffic and receive replies, but the internet cannot initiate inbound.</li><li>The doorman is a <strong>security group</strong>: attached to the instance itself, allow-rules only, and <strong>stateful</strong> — return traffic for an allowed connection flows automatically.</li><li>The turnstile is a <strong>network ACL</strong>: attached to the subnet, allow <em>and</em> deny rules, evaluated in number order, and <strong>stateless</strong> — replies must be explicitly allowed too.</li></ul><p>A public subnet is nothing mystical: it is simply a subnet whose route table sends <code>0.0.0.0/0</code> to the Internet Gateway.</p>"
    },
    {
      name: "How it actually works",
      html: "<p>The part that reframes everything: a VPC is not a physical network. There are no cables that belong to you. It is a <strong>configuration overlaid on AWS's physical network</strong> — a mapping service that every Nitro host consults, which encapsulates your packets and delivers them only to destinations your VPC's tables say exist. Two subnets in the same VPC are not nearer to each other than two subnets in different VPCs; distance is an illusion, and routing is a table lookup, not a topology.</p><p>Mechanics that matter:</p><ul><li>Route resolution is <strong>longest-prefix match</strong>. Every route table contains an immovable <code>local</code> route for the whole VPC CIDR, which is why intra-VPC traffic works with zero configuration and why you cannot override it to filter internal traffic with routes.</li><li>Security group statefulness is implemented with <strong>connection tracking</strong> on the host — the doorman's memory is literally a conntrack table, with entry limits on large instances.</li><li>Security groups can reference <strong>other security groups</strong> as sources — allow from the web tier's group rather than from IP ranges — which is how you build tiers that survive IP churn.</li><li>NACLs being stateless means return traffic uses <strong>ephemeral ports</strong> (1024-65535); forget to allow that range outbound and inbound replies die mysteriously.</li></ul>"
    },
    {
      name: "The sharp edges",
      html: "<p>The classic cuts:</p><ul><li><strong>Security groups cannot deny.</strong> Need to block one hostile IP? That is a NACL deny rule — the exam's favorite distinction.</li><li><strong>The ephemeral-port trap:</strong> a NACL allowing inbound 443 but not outbound 1024-65535 breaks every response. Stateless means both directions, always.</li><li><strong>NAT Gateways are zonal and metered.</strong> One per AZ for resilience, and every gigabyte through them is billed — S3 traffic should use a gateway VPC endpoint instead, which is free and rides the route table.</li><li><strong>Peering is not transitive.</strong> A-B and B-C peered does not connect A to C; hub-and-spoke at scale is Transit Gateway. And peering forbids overlapping CIDRs — plan address space before, not after.</li><li><strong>Subnets are AZ-scoped</strong>, so a multi-AZ tier means one subnet per AZ per tier, each wired to the right route table.</li></ul><p>Where the analogy lies: there are no corridors. Nothing is adjacent to anything; a subnet provides zero isolation by itself — only its route table, NACL, and the security groups inside it do. And the doorman does not stand at a door: he runs on the virtualization host itself, enforcing rules before packets ever reach your instance.</p><p><strong>Exam reflex:</strong> stateful and allow-only means security group; stateless, ordered rules, or blocking a specific IP means network ACL.</p>"
    }
  ]
});

/* ================= 4. ec2 — purchase-option economics ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-ec2",
  moduleId: "ec2",
  title: "Purchase options: on-demand, reserved, and spot economics",
  levels: [
    {
      name: "The analogy",
      html: "<p>A big hotel sells the exact same rooms three different ways. You can <strong>walk in</strong> tonight and pay the rack rate: maximum flexibility, no commitment, highest price per night. Or your company can sign a <strong>one- or three-year contract</strong> for the fifty rooms its consultants occupy every single night — the hotel loves guaranteed revenue and hands you a discount approaching two-thirds off. Or you can take a <strong>standby room</strong>: whatever is unsold tonight, at up to ninety percent off — with one brutal catch. When a full-paying guest shows up, the hotel knocks on your door and you have <strong>two minutes</strong> to grab your bag and leave.</p><p>No sane travel manager picks just one. The steady nightly crew goes on contract. The unpredictable-but-important trips pay rack rate. And the intern scanning archives — who can happily move rooms mid-task — sleeps gloriously cheap in standby. Blending the three is the entire game.</p>"
    },
    {
      name: "The simple model",
      html: "<p>Same compute, three prices:</p><ul><li><strong>On-Demand</strong> is the rack rate: per-second billing, no commitment, the price everything else is discounted from. Use it for spiky, unpredictable, or short-lived workloads.</li><li><strong>Reserved Instances and Savings Plans</strong> are the contract: commit to one or three years and save up to roughly 72 percent. Savings Plans commit to a dollars-per-hour spend; Compute Savings Plans apply across instance family, size, Region — even Fargate and Lambda — while EC2 Instance Savings Plans lock a family in a Region for a deeper cut. Use them for your measured, steady baseline.</li><li><strong>Spot</strong> is the standby room: AWS's spare capacity at up to 90 percent off, reclaimable with a <strong>two-minute interruption notice</strong>. Use it only for workloads that tolerate interruption — batch, CI, stateless workers, big data.</li></ul><p>The canonical architecture answer: Reserved or Savings Plans for the baseline you always run, On-Demand for the predictable-but-variable layer, Spot for fault-tolerant burst.</p>"
    },
    {
      name: "How it actually works",
      html: "<p>The mechanics under each price:</p><ul><li><strong>Reservations are billing constructs, mostly.</strong> A <em>regional</em> RI or a Savings Plan is a discount matcher: it scans your running usage each hour and applies the discount to whatever matches. It guarantees you money, not machines. A <em>zonal</em> RI — pinned to one AZ — additionally reserves capacity. So do standalone <strong>On-Demand Capacity Reservations</strong>, which need no term commitment at all: capacity assurance and billing discount are separate levers you can combine.</li><li><strong>Standard vs Convertible RIs:</strong> standard is cheaper; convertible can be exchanged for different families along the way.</li><li><strong>Spot pricing</strong> is no longer a live auction; prices move smoothly with long-term supply and demand per instance pool (an instance type in an AZ). Interruptions happen when a pool shrinks, not because someone outbid you. You choose interruption behavior — terminate, stop, or hibernate — and diversify across many pools using Auto Scaling groups with mixed instances and a <strong>price-capacity-optimized</strong> allocation strategy, so one pool drying up does not strand the fleet.</li><li><strong>Dedicated Hosts</strong> give you a whole physical server with socket and core visibility — required for bring-your-own per-socket licenses (Windows Server, SQL Server, Oracle). <strong>Dedicated Instances</strong> merely promise hardware not shared with other tenants, without that visibility.</li></ul>"
    },
    {
      name: "The sharp edges",
      html: "<p>Where the money and the exam points leak away:</p><ul><li><strong>A regional RI is not a capacity guarantee.</strong> During a capacity crunch you can hold a discount for an instance you cannot launch. If the question says <em>must be guaranteed to launch</em>, the answer involves a zonal RI or a Capacity Reservation.</li><li><strong>Spot disqualifies itself</strong> the moment a scenario says the job cannot be interrupted, must finish by a deadline with no checkpointing, or holds unreplicated state. Ninety percent off a job that never completes is not a discount.</li><li><strong>Commitment cuts both ways:</strong> you pay a Savings Plan's hourly commitment whether you use it or not — over-committing on a shrinking workload converts savings into pure waste. Commit to the floor, not the average.</li><li><strong>Dedicated Host vs Dedicated Instance</strong> is a beloved trap: per-socket or per-core BYOL licensing always means Host.</li></ul><p>Where the analogy lies: an evicted hotel guest loses the room's contents, but a Spot instance can <em>stop or hibernate</em> and later resume with its EBS volumes intact. And unlike a hotel, capacity is not one building: diversifying across instance pools means standby almost never truly runs out for a flexible fleet.</p><p><strong>Exam reflex:</strong> steady baseline means Savings Plan or RI; interruptible and fault-tolerant means Spot; per-socket BYOL licensing means Dedicated Host.</p>"
    }
  ]
});

/* ================= 5. elb-asg — target tracking + health checks ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-elb-asg",
  moduleId: "elb-asg",
  title: "Target tracking and health checks: the thermostat",
  levels: [
    {
      name: "The analogy",
      html: "<p>Nobody heats a building by telling the janitor to run exactly four heaters. You set a <strong>thermostat</strong> to 21 degrees and walk away. Cold snap? The system notices the temperature sagging and switches more heaters on. Sunny afternoon? It quietly shuts some down. You declared the <em>outcome</em>; the machinery works out the <em>count</em>, minute by minute, forever.</p><p>Two more pieces make it trustworthy. Every heater has a <strong>smoke detector</strong> watching it: a heater that starts smoking is unplugged, wheeled out, and a fresh one is wheeled in — automatically, at 3 a.m., with nobody paged. And the building's <strong>duct system</strong> only pushes air through vents connected to working heaters, so a dying heater never chills the rooms it used to serve.</p><p>The elegance is what you stopped doing: no one counts heaters, no one watches the weather forecast, no one inspects heaters on a Sunday. You picked a temperature. Everything else is plumbing.</p>"
    },
    {
      name: "The simple model",
      html: "<p>The mapping:</p><ul><li>The <strong>thermostat setting</strong> is a <strong>target tracking scaling policy</strong>: keep average CPU at 50 percent, or keep requests-per-target at 1000. You declare the metric value; the Auto Scaling group adjusts instance count to hold it.</li><li>The <strong>heaters</strong> are EC2 instances in the <strong>Auto Scaling group</strong>, bounded by a min and max size — the smallest and largest number of heaters the building may ever run.</li><li>The <strong>smoke detector</strong> is the <strong>health check</strong>. The ASG can watch basic EC2 status, or — much better — trust the <strong>load balancer's health check</strong>, which probes the actual application endpoint. Unhealthy instances are terminated and replaced automatically.</li><li>The <strong>ducts</strong> are the <strong>Elastic Load Balancer</strong>, which routes traffic only to targets currently passing health checks.</li></ul><p>Together they form one loop: the load balancer spreads work and reports health, the health checks cull the broken, and target tracking resizes the fleet so the metric stays pinned to your number.</p>"
    },
    {
      name: "How it actually works",
      html: "<p>Target tracking is not magic — it manufactures <strong>CloudWatch alarms</strong> for you: one to scale out when the metric runs above target, one to scale in when it runs below, with the scale-in side deliberately conservative (slower, smaller steps) because removing capacity is the dangerous direction. The math only works if the metric is <strong>inversely proportional to capacity</strong> — average CPU halves when you double the fleet, so it works; a queue's total depth does not care how many workers exist, so it needs a computed backlog-per-instance metric instead.</p><p>Timing parameters carry the real engineering:</p><ul><li><strong>Instance warmup</strong> tells the ASG how long a new instance takes before its metrics count — scale out during boot-storms without it and you badly overshoot.</li><li><strong>Health check grace period</strong> protects booting instances from being judged unhealthy while the app is still starting.</li><li><strong>Deregistration delay</strong> (connection draining) lets in-flight requests finish on an instance being removed before it is cut from the ducts.</li></ul><p>Health check wiring is a deliberate choice: by default the ASG only watches EC2 status checks (is the VM alive), and you must explicitly enable <strong>ELB health checks</strong> so the ASG also replaces instances whose <em>application</em> is failing. Beyond target tracking sit step scaling (manual thresholds), scheduled scaling (known daily patterns), and predictive scaling (forecast-driven pre-warming).</p>"
    },
    {
      name: "The sharp edges",
      html: "<p>How thermostats burn houses down:</p><ul><li><strong>The zombie fleet:</strong> ASG on default EC2 health checks plus a crashed application process equals instances that are healthy to the ASG and dead to users — the load balancer pulls them from rotation but the ASG never replaces them. Enabling ELB health checks on the ASG is the fix, and a favorite exam answer.</li><li><strong>The kill loop:</strong> a grace period shorter than app startup means every new instance is executed mid-boot, which triggers another launch, forever, while the fleet never actually grows.</li><li><strong>Oscillation:</strong> warmup set too low makes the controller overshoot then over-correct — thrashing that adds cost and churn. Scale-in protection exists for instances holding long-lived work.</li><li><strong>Wrong metric:</strong> tracking a value capacity cannot influence (external API latency, total queue depth) sends the fleet to max and pins it there.</li><li><strong>Deep health checks that check dependencies</strong> (database reachable?) can fail the whole fleet simultaneously during a dependency blip — the ASG then replaces healthy instances en masse. Shallow-check your own process, alarm on dependencies separately.</li></ul><p>Where the analogy lies: heaters warm a room in seconds; instances take minutes to boot, so the controller is always steering with lag — which is exactly why warmup, grace periods, and predictive scaling exist at all.</p><p><strong>Exam reflex:</strong> <em>maintain a metric at a value</em> means target tracking; <em>replace instances failing app-level checks</em> means ASG with ELB health checks enabled.</p>"
    }
  ]
});

/* ================= 6. s3 — object storage vs filesystem ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-s3",
  moduleId: "s3",
  title: "Object storage: valet parking, not a garage you walk into",
  levels: [
    {
      name: "The analogy",
      html: "<p>A parking garage you walk into works like this: you choose floor 3, bay 12, you park, and later you can wander back with a wrench and change a tire right there in the spot. You know exactly where your car is because <em>you</em> put it there.</p><p><strong>Valet parking is a different contract entirely.</strong> You hand the whole car over the counter and receive a <strong>claim ticket</strong>. Where the car physically sits is none of your business — it might be in any of three lots across town. You cannot stroll the aisles browsing cars. You cannot change a tire in place: you present the ticket, the whole car comes back, you modify it, and you hand the whole car in again — it may well end up parked somewhere new.</p><p>In exchange for giving up the wrench and the wandering, this valet is superhuman: it never loses a car, never runs out of space, serves a million customers at the same counter simultaneously, and honors a ticket decades later. The ticket is everything. The exact ticket.</p>"
    },
    {
      name: "The simple model",
      html: "<p>The car is an <strong>object</strong> — the bytes plus its metadata. The claim ticket is the <strong>key</strong>. The valet company is <strong>S3</strong>, and the lots across town are the multiple Availability Zones where S3 automatically keeps redundant copies, which is where the famous eleven-nines durability comes from.</p><p>Two consequences fall straight out of the analogy:</p><ul><li><strong>There are no folders.</strong> A key like <code>photos/2024/cat.jpg</code> is one flat string — the slashes are just writing on the ticket. The console draws folders by grouping tickets with a shared <strong>prefix</strong>, but no directory tree exists to walk, rename, or lock.</li><li><strong>There are no partial edits.</strong> Every write replaces the entire object. There is no append, no in-place update of byte 4,096 — retrieve, modify, put back whole.</li></ul><p>Access is by API over HTTPS — a counter transaction, not a mounted disk. And unlike most real valets, S3 now gives <strong>strong read-after-write consistency</strong>: the instant your PUT succeeds, any GET returns the new car, not the old one.</p>"
    },
    {
      name: "How it actually works",
      html: "<p>The flat keyspace is what buys the scale. With no directory tree to lock and no hierarchy to keep consistent, S3 partitions the keyspace by prefix and scales each partition independently: at least <strong>3,500 PUT and 5,500 GET requests per second per prefix</strong>, with more prefixes meaning effectively unlimited aggregate throughput. Durability comes from erasure-coding and redundantly storing every object across at least three AZs — the valet does not park your car carefully; it shreds it into mathematically recoverable pieces across town.</p><p>Mechanics a senior engineer should hold:</p><ul><li><strong>Multipart upload</strong> is mandatory over 5 GB per PUT (objects max out at 5 TB) and wise above 100 MB: parallel parts, independent retries, then an atomic completion call.</li><li><strong>Versioning</strong> means the valet keeps every old car under the same ticket; deletes just add a <em>delete marker</em> on top, which is why versioning plus MFA delete is the classic ransomware and fat-finger defense.</li><li><strong>Storage classes</strong> are cheaper lots with slower or costlier retrieval — Standard, Intelligent-Tiering, Standard-IA, One Zone-IA, and the Glacier tiers — moved between by <strong>lifecycle rules</strong>.</li><li><strong>Presigned URLs</strong> are lending your ticket: a time-limited URL carrying your credentials' authority, letting anyone PUT or GET one object briefly.</li><li>Encryption at rest is on by default (SSE-S3), upgradeable to SSE-KMS for auditable, policy-controlled keys.</li></ul>"
    },
    {
      name: "The sharp edges",
      html: "<p>Where treating the valet like a garage draws blood:</p><ul><li><strong>No rename, no move.</strong> Renaming is copy-then-delete — for a million objects under a prefix, that is a million copies. Naming schemes are close to permanent; design keys around access patterns up front.</li><li><strong>Strong consistency is not locking.</strong> Two simultaneous PUTs to one key: last writer wins, silently. Coordination needs versioning or S3's conditional writes, not hope.</li><li><strong>Class minimums bite:</strong> Standard-IA charges a 30-day minimum and per-GB retrieval; Glacier tiers carry 90 or 180-day minimums, and Deep Archive restores take hours. Lifecycle churn on short-lived objects can cost more than Standard.</li><li><strong>One Zone-IA</strong> abandons the lots-across-town redundancy — one AZ, genuinely less durable against AZ loss; only for re-creatable data.</li><li><strong>Mounting S3 as a disk</strong> (Mountpoint and friends) suits sequential reads and writes, not random-access POSIX workloads — the counter is still a counter even if you disguise it as a door.</li></ul><p>Where the analogy lies: a valet fetches one car for one owner, but S3 serves the same object to millions of readers concurrently and will happily front a static website or a data lake — a claim counter with effectively infinite parallel windows.</p><p><strong>Exam reflex:</strong> durable, unlimited, HTTP-accessed, whole-object storage means S3; anything demanding POSIX semantics, file locking, or in-place partial writes means EFS or EBS instead.</p>"
    }
  ]
});

/* ================= 7. block-file — block vs file vs object ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-block-file",
  moduleId: "block-file",
  title: "Block vs file vs object: three ways to store bytes",
  levels: [
    {
      name: "The analogy",
      html: "<p>A storage company sells the same square footage three ways.</p><p><strong>Service one: the private room.</strong> An empty room of numbered shelves, your padlock, one renter inside at a time. The company has no idea what a document even is — slot 4,017 holds whatever you put there. You bring your own filing system, your own index, your own labels. Total control, total responsibility, and it is right next door, so fetching anything is instant.</p><p><strong>Service two: the shared records room.</strong> Cabinets, drawers, folders inside folders, run by a meticulous clerk. Whole teams walk in at once, and the moment someone updates a folder, everyone else sees the change. The clerk enforces order, permissions, and who-edits-what.</p><p><strong>Service three: the claim-ticket warehouse.</strong> A counter out front, an effectively infinite warehouse behind it. Hand an item over, get a ticket. You always deposit and retrieve <em>whole items</em> — nobody edits anything on the shelf — but the warehouse never fills, never loses a thing, and serves the entire city at once.</p>"
    },
    {
      name: "The simple model",
      html: "<p>The three services are the three storage models:</p><table><thead><tr><th>Analogy</th><th>Model</th><th>AWS</th><th>Access</th></tr></thead><tbody><tr><td>Private room of numbered shelves</td><td><strong>Block</strong></td><td>EBS (and instance store)</td><td>Raw numbered blocks; you format a filesystem on top; one instance at a time, in one AZ</td></tr><tr><td>Shared records room with a clerk</td><td><strong>File</strong></td><td>EFS, FSx</td><td>A real filesystem over the network — paths, permissions, locks — mounted by many clients across AZs at once</td></tr><tr><td>Claim-ticket warehouse</td><td><strong>Object</strong></td><td>S3</td><td>Whole objects by key over HTTPS; no hierarchy, no in-place edits, near-infinite scale</td></tr></tbody></table><p>The choosing question is the <strong>unit of access</strong>: if software must edit bytes in place at microsecond latency — databases, boot volumes — that is block. If many machines must share one hierarchy with POSIX semantics, that is file. If you read and write whole items at massive scale over the network, that is object.</p>"
    },
    {
      name: "How it actually works",
      html: "<p>Each model's mechanics follow from its contract:</p><ul><li><strong>Block (EBS):</strong> the OS sees a raw device and runs its own filesystem and page cache over it, giving sub-millisecond latency — which is why databases require it. You provision performance explicitly: gp3 decouples IOPS and throughput from size; io2 serves the high end. A volume is replicated <em>within one AZ only</em> and attaches to one instance (multi-attach on io2 exists, but demands a cluster-aware filesystem — ext4 mounted twice corrupts). Durability across AZs comes from <strong>snapshots</strong>, which are incremental and land in S3.</li><li><strong>File (EFS/FSx):</strong> a server-side filesystem spoken over the network — NFS for EFS (Linux, regional, spans AZs, elastic sizing, pay per GB used), SMB with Active Directory for FSx for Windows, Lustre for HPC scratch that can hydrate from and flush to S3. Every operation is a network round trip, so per-operation latency is inherently higher than block; throughput scales wide instead.</li><li><strong>Object (S3):</strong> the flat keyspace and whole-object writes remove the coordination that limits filesystems, buying eleven-nines durability, effectively unlimited capacity, and the lowest cost per GB — paid for in per-request pricing and no in-place mutation.</li></ul><p>One instinct: as you go block, file, object — per-operation latency rises, sharing widens, scale explodes, and price per GB falls.</p>"
    },
    {
      name: "The sharp edges",
      html: "<p>Where the models refuse to substitute for each other:</p><ul><li><strong>EBS is AZ-locked.</strong> It cannot attach across AZs, ever. Cross-AZ mobility is snapshot-and-restore; that alone eliminates it from any shared-storage answer.</li><li><strong>EFS is not database storage.</strong> Its per-operation network latency makes it a poor home for transaction logs and random 4K I/O; scenario says database, answer says EBS or a managed database — never EFS, never S3.</li><li><strong>Protocol decides the FSx flavor:</strong> SMB, Windows, or Active Directory means FSx for Windows File Server; Linux NFS shared across many instances means EFS; HPC or machine-learning scratch tied to S3 means FSx for Lustre.</li><li><strong>Object is not a filesystem</strong> no matter what mounts it: no rename, no append, no locks — an application doing partial in-place writes against S3 is an outage in rehearsal.</li><li><strong>EFS pricing</strong> is per GB stored but noticeably pricier per GB than S3 — hierarchy and semantics are what you are paying for.</li></ul><p>Where the analogy lies: the three services sound like a quality ladder from private to cheap, but they are orthogonal contracts — the claim-ticket warehouse (S3) is simultaneously the cheapest, the most durable, and the most scalable of the three. And the private room is not next door; EBS blocks travel a network too — Nitro just makes the round trip short enough to pretend.</p><p><strong>Exam reflex:</strong> in-place byte-level writes or a database means block (EBS); shared POSIX across many instances means file (EFS, or FSx when Windows or Lustre is named); internet-scale whole objects mean S3.</p>"
    }
  ]
});

/* ================= 8. ha-dr — RTO/RPO and paying for parallel universes ================= */
window.COURSE.registerExplainer({
  id: "x-intuition-ha-dr",
  moduleId: "ha-dr",
  title: "RTO, RPO, and paying for parallel universes",
  levels: [
    {
      name: "The analogy",
      html: "<p>A theater lives in terror of a dark stage. If tonight's star collapses mid-season, exactly two questions matter: <strong>how long may the curtain stay down</strong>, and <strong>how much of the latest script changes may the replacement not know?</strong></p><p>The theater can prepare at four price points. Cheapest: keep every script archived and, if disaster strikes, <em>hire and rehearse a new actor from scratch</em> — the curtain stays down for days. Better: keep an <strong>understudy who re-reads the script every Sunday</strong> — ready in hours, but ignorant of this week's rewrites. Better still: an understudy <strong>in costume, in the wings, mouthing every line in real time</strong> — on stage in minutes, current to the last scene. Most expensive: run a <strong>full second cast performing the same show in a second theater across town</strong>, both selling tickets every night. If one theater burns down, the audience is simply redirected; nothing was ever lost.</p><p>That last option is literally paying for a parallel universe. Magnificent — and double the payroll, forever.</p>"
    },
    {
      name: "The simple model",
      html: "<p>The two questions have names: curtain-down time is <strong>RTO</strong> (Recovery Time Objective — how long until service is restored) and script staleness is <strong>RPO</strong> (Recovery Point Objective — how much recent data you may lose). Business requirements set both numbers <em>first</em>; the numbers then select the strategy, and each step up multiplies the standing cost:</p><ol><li><strong>Backup and restore</strong> — the new-hire actor: data backed up to another Region, infrastructure rebuilt on demand. RTO in hours to a day; RPO equals your backup interval. Cheapest.</li><li><strong>Pilot light</strong> — the Sunday understudy: the data layer replicates continuously to the DR Region, but compute is off, existing only as templates. RTO tens of minutes to hours; RPO near zero.</li><li><strong>Warm standby</strong> — costumed in the wings: a complete but scaled-down copy runs live; failover means scaling it up and shifting traffic. RTO in minutes.</li><li><strong>Multi-site active-active</strong> — the second cast: full capacity in both Regions serving real traffic. RTO near zero, RPO near zero, roughly double the bill.</li></ol><p>Route 53 plays the box office, redirecting the audience to whichever theater is open.</p>"
    },
    {
      name: "How it actually works",
      html: "<p><strong>RPO is set by how data moves.</strong> Snapshots and backups give an RPO equal to their schedule — nightly backup, up to 24 hours of lost writes. Continuous asynchronous replication shrinks RPO to seconds: Aurora Global Database typically holds cross-Region lag near one second, DynamoDB global tables replicate multi-Region active-active, S3 Cross-Region Replication copies new objects continuously. True zero RPO demands synchronous replication, and physics confines that to within a Region (Multi-AZ) — cross-Region round trips make synchronous writes too slow, which is why <em>Multi-AZ is high availability, while DR across Regions is almost always asynchronous</em>.</p><p><strong>RTO is set by what is already running plus how fast traffic moves.</strong> The chain is detection (health checks, alarms), promotion (a replica becomes the writer), capacity (already-warm, or launched now from IaC and AMIs), and redirection (Route 53 failover records with health checks, or Global Accelerator shifting at the network layer with no DNS wait).</p><ul><li><strong>Pilot light</strong> keeps the data live and the compute cold: replicas replicating, AMIs and templates ready, nothing billing but storage and the database.</li><li><strong>Warm standby</strong> runs everything at minimum size; failover is an ASG scale-up plus a DNS flip.</li><li><strong>Active-active</strong> adds the hard part: both sides accepting writes, so conflict resolution (global tables use last-writer-wins) becomes an application-design problem, not an infrastructure checkbox.</li></ul>"
    },
    {
      name: "The sharp edges",
      html: "<p>Where recovery plans die:</p><ul><li><strong>A backup in the same Region is not DR.</strong> If the scenario says survive a Region failure, backups, snapshots, and AMIs must be <em>copied to another Region</em> — an unreplicated backup shares its Region's fate.</li><li><strong>Failover that launches capacity can fail exactly when needed.</strong> During a real regional event, everyone fails over at once and the DR Region gets crowded; pilot light quietly assumes instances will launch on demand. Warm standby and capacity reservations are what certainty costs.</li><li><strong>An untested plan is fiction.</strong> Replication that has never been failed over, runbooks never rehearsed — game days are part of the architecture, not an afterthought.</li><li><strong>DNS is sticky:</strong> TTLs and misbehaving resolvers stretch real RTO past the theoretical flip; Global Accelerator sidesteps DNS entirely with static anycast IPs.</li><li><strong>The exam punishes over-buying.</strong> Active-active for a stated RTO of four hours is wrong precisely because it works — pick the <em>cheapest</em> strategy that meets the stated numbers.</li></ul><p>Where the analogy lies: a play's script changes weekly; production data is rewritten continuously by the audience itself, so even the costumed understudy trails by a heartbeat of replication lag — near-zero RPO is not zero. And two casts can perform independently, but two Regions accepting the same writes must reconcile them.</p><p><strong>Exam reflex:</strong> read the stated RTO and RPO, then choose the cheapest tier that satisfies them — hours means backup/restore or pilot light, minutes means warm standby, near-zero means multi-site active-active.</p>"
    }
  ]
});
